### ISSUE TITLE
Error while building the docker-compose

### ISSUE THREAD

**Issue by comptemob** [bibbox/app-openspecimen#1]
Error while building the docker-compose:

`docker-compose up`

`ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid service name '§§INSTANCE-openspecimen-web' - only [a-zA-Z0-9\._\-] characters are allowed`

**Comment by lomadi** [comment]
this is a template for a docker file, you have to install it through the bibbox app store 
http://demo.bibbox.org
http://bibbox.readthedocs.io/en/latest/
or you replace manually the variables marked by §§
