### ISSUE TITLE
"Error initializing app" - issue

### ISSUE THREAD

**Issue by mjschmine** [bibbox/app-openspecimen#2]
Dear all,
after installing an openSpecimen app the error message shown below occurs. OpenSpecimen is not reachable (HTTP error 404).  After a bit research I found that MariaDB is not supported anymore (see [here](http://forums.openspecimen.org/t/cannot-start-openspecimen-app-after-upgrade-attempt-from-4-to-6-1/1356)), so I am wondering why a MariaDB (instead of MySQL) container was built. 

Any ideas how to fix that in a Bibbox way?

Thank you very much.

> 05-Nov-2019 09:11:23.216 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class com.krishagni.catissueplus.core.init.AppServletContextListener
>  java.lang.RuntimeException: Error initializing app
> 	at com.krishagni.catissueplus.core.init.AppServletContextListener.contextInitialized(AppServletContextListener.java:61)
> 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4900)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5363)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
> 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:973)
> 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> 	at com.krishagni.catissueplus.core.init.AppServletContextListener.getContextName(AppServletContextListener.java:77)
> 	at com.krishagni.catissueplus.core.init.AppServletContextListener.contextInitialized(AppServletContextListener.java:46)
> 	... 13 more
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> 	at java.lang.String.substring(String.java:1931)
> 	at com.krishagni.catissueplus.core.init.AppServletContextListener.getContextName(AppServletContextListener.java:74)
> 	... 14 more

**Comment by S-Streit** [comment]
Sorry for any inconvenience should've been fixed.
