### ISSUE TITLE
Connection with Cloud SQL

### ISSUE THREAD

**Issue by sumitrathi95** [bibbox/app-openspecimen#6]
Hello Team,

I was just trying to deploy the and run the docker-compose but I am trying to connect it with Cloud Mysql 5.7. I am getting various errors. When I removed the links from docker-compose file it failed. Also, I tried to put MySQL IP address as host, it fails. Can you please help me with this situation.

Thanks in advance.

**Comment by S-Streit** [comment]
Any news on the issue ? Does the jdbc connector support Cloud MySQL ?

**Comment by S-Streit** [comment]
Closing this for now. If anything occurs just reopen
